import AppKit
import Foundation
import Testing
@testable import ProsoponReview

/// The artwork is a resource, and a missing resource is silent.
///
/// Nino recorded this trap and it is the reason these assertions exist: `Image(name,
/// bundle: .module)` against a SwiftPM resource returned an empty image, the splash
/// rendered as a bare gradient, and every test about the layout still passed — because a
/// missing image is a perfectly valid `Image`. Loading by URL turns that into a `nil`
/// something can be asserted about, and this is the assertion.
@Suite("Brand artwork")
struct BrandTests {

    @Test("the key art is in the bundle and decodes")
    func bannerLoads() throws {
        // If this fails: either Package.swift stopped copying
        // Sources/ProsoponReview/Resources, or scripts/make_assets.py has not been run.
        let banner = try #require(Brand.banner, "AboutBanner.jpg did not load")
        #expect(banner.size.width > 0 && banner.size.height > 0)
    }

    @Test("the key art is the shape the panel reserves for it")
    func bannerIsTheRightShape() throws {
        // 640 x 250 at 2x. A square would be letterboxed into the band and the face would
        // come out a quarter of the size the layout assumes.
        let banner = try #require(Brand.banner)
        let aspect = banner.size.width / banner.size.height
        #expect(abs(aspect - 640.0 / 250.0) < 0.02, "banner is \(banner.size), aspect \(aspect)")
    }

    @Test("the mark is in the bundle and is square")
    func markLoads() throws {
        let mark = try #require(Brand.mark, "AppMark.png did not load")
        #expect(mark.size.width == mark.size.height)
        #expect(mark.size.width >= 128, "the lockup draws it at 49pt, so it needs 2x at least")
    }

    @Test("the app bundle's icon is checked in beside the sources")
    func iconIsCheckedIn() throws {
        // Not a bundled resource — `review.sh` copies it into the .app — so it is checked
        // by path. Regenerated by scripts/make_assets.py; checked in so that building
        // needs neither Python nor Pillow.
        let icon = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // ProsoponReviewTests
            .deletingLastPathComponent()   // Tests
            .deletingLastPathComponent()   // repository root
            .appendingPathComponent("Resources/Prosopon.icns")
        #expect(FileManager.default.fileExists(atPath: icon.path), "missing \(icon.path)")
    }

    @Test("the footer carries the house credit and both sites")
    func footerMatchesTheHouse() {
        // Word for word as the other applications on this machine carry it, so opening
        // any of them reads as opening the same program.
        #expect(AboutText.credit == "Created by Charis Tsevis, with the help of Claude Code.")
        #expect(Brand.makerSiteLabel == "tsevis.com")
        #expect(Brand.githubLabel == "github.com/tsevis")
        #expect(Brand.makerSite.host()?.contains("tsevis.com") == true)
        #expect(Brand.githubSite.absoluteString == "https://github.com/tsevis")
    }

    @Test("the panel's words are there to read")
    func textIsPresent() {
        #expect(AboutText.story.count >= 4)
        #expect(AboutText.legal.count >= 2)
        #expect(AboutText.story.allSatisfy { !$0.isEmpty })

        // The three coordinates are the thing the panel exists to explain; a rewrite that
        // loses them has lost the point of the page.
        let story = AboutText.story.joined(separator: " ")
        for coordinate in ["512, 512", "1536, 512", "1024, 1664"] {
            #expect(story.contains(coordinate), "the story no longer names \(coordinate)")
        }

        // Every model that is run gets named where the licences are.
        let legal = AboutText.legal.joined(separator: " ")
        for credit in ["Vision", "InsightFace", "ONNX Runtime"] {
            #expect(legal.contains(credit), "the licences no longer name \(credit)")
        }
    }
}
